component_depth: 6
languages:
- javascript
- ruby

- name: javascript
  production:
    exclude:
      - ./spec/*
  test:
    include:
      - ./spec/*
- name: ruby
  production:
    exclude:
      - ./spec/*
  test:
    include:
      - ./spec/*